/**
 * Maya Event Vocabulary
 *
 * Maya-specific event types. Reuses shared event infrastructure.
 */

export { emitEvent } from '../events/domain-events.js';
export type { DomainEvent } from '../events/domain-events.js';

export const MAYA_EVENT_TYPES = {
  OPPORTUNITY_DISCOVERED: 'OPPORTUNITY_DISCOVERED',
  OPPORTUNITY_UPDATED: 'OPPORTUNITY_UPDATED',
  OPPORTUNITY_MATERIAL_CHANGE: 'OPPORTUNITY_MATERIAL_CHANGE',
  MAYA_REVIEW_REQUIRED: 'MAYA_REVIEW_REQUIRED',
  MAYA_REVIEW_COMPLETED: 'MAYA_REVIEW_COMPLETED',
  MAYA_EVALUATE: 'MAYA_EVALUATE',
  MAYA_WATCH: 'MAYA_WATCH',
  MAYA_PASS: 'MAYA_PASS',
  SLACK_OPPORTUNITY_BRIEF_POSTED: 'SLACK_OPPORTUNITY_BRIEF_POSTED',
  SLACK_PROJECTION_FAILED: 'SLACK_PROJECTION_FAILED',
  SEND_TO_CAPTURE: 'SEND_TO_CAPTURE',
  MAYA_MORE_RESEARCH_REQUESTED: 'MAYA_MORE_RESEARCH_REQUESTED',
  CANDIDATE_DISMISSED: 'CANDIDATE_DISMISSED',
} as const;

export type MayaEventType = (typeof MAYA_EVENT_TYPES)[keyof typeof MAYA_EVENT_TYPES];
