/**
 * James Capture Event Vocabulary
 *
 * Capture-specific event types. Uses shared event infrastructure.
 */

export { emitEvent } from '../events/domain-events.js';
export type { DomainEvent } from '../events/domain-events.js';

export const CAPTURE_EVENT_TYPES = {
  CAPTURE_STARTED: 'CAPTURE_STARTED',
  JAMES_ASSESSMENT_STARTED: 'JAMES_ASSESSMENT_STARTED',
  JAMES_ASSESSMENT_COMPLETED: 'JAMES_ASSESSMENT_COMPLETED',
  JAMES_RESEARCH_REQUIRED: 'JAMES_RESEARCH_REQUIRED',
  SPECIALIST_TASK_REQUESTED: 'SPECIALIST_TASK_REQUESTED',
  SPECIALIST_TASK_COMPLETED: 'SPECIALIST_TASK_COMPLETED',
  SPECIALIST_TASK_FAILED: 'SPECIALIST_TASK_FAILED',
  JAMES_RESYNTHESIS_STARTED: 'JAMES_RESYNTHESIS_STARTED',
  JAMES_RESYNTHESIS_COMPLETED: 'JAMES_RESYNTHESIS_COMPLETED',
  CAPTURE_RECOMMENDATION_READY: 'CAPTURE_RECOMMENDATION_READY',
  EXECUTIVE_MORE_RESEARCH_REQUESTED: 'EXECUTIVE_MORE_RESEARCH_REQUESTED',
  PURSUIT_AUTHORIZED: 'PURSUIT_AUTHORIZED',
  PURSUIT_NO_GO: 'PURSUIT_NO_GO',
  CAPTURE_BUDGET_EXHAUSTED: 'CAPTURE_BUDGET_EXHAUSTED',
  // Future-consumer events (no live integration in 3B)
  NOTION_SYNC_REQUESTED: 'NOTION_SYNC_REQUESTED',
  PORTFOLIO_TRACKING_REQUIRED: 'PORTFOLIO_TRACKING_REQUIRED',
} as const;

export type CaptureEventType = (typeof CAPTURE_EVENT_TYPES)[keyof typeof CAPTURE_EVENT_TYPES];
