/**
 * Deliverables Database Operations
 *
 * Manages work products generated by agents including:
 * - Go/No-Go Memos (James)
 * - Research Briefs (David)
 * - Partner Shortlists (Rosa)
 * - Tech Risk Assessments (Marcus)
 * - Executive Insights (Patricia)
 * - Capture Plans (James/Patricia)
 * - Weekly Rollups (Patricia)
 */

import { createClient } from '@supabase/supabase-js';

// ============================================================
// Types
// ============================================================

export type DeliverableType =
  | 'go_no_go_memo'
  | 'research_brief'
  | 'partner_shortlist'
  | 'tech_assessment'
  | 'executive_insight'
  | 'capture_plan'
  | 'weekly_rollup';

export type DeliverableStatus = 'draft' | 'ready' | 'actioned' | 'archived';

export interface Deliverable {
  id: string;
  deliverable_type: DeliverableType;
  title: string;
  owner_agent: string;
  opportunity_id: string | null;
  opportunity_title: string | null;
  status: DeliverableStatus;
  content: string | null;
  notion_page_id: string | null;
  source_post_ids: string[];
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

export interface CreateDeliverableInput {
  deliverable_type: DeliverableType;
  title: string;
  owner_agent: string;
  opportunity_id?: string;
  opportunity_title?: string;
  content: string;
  source_post_ids?: string[];
  metadata?: Record<string, unknown>;
}

// ============================================================
// Database Client
// ============================================================

function getSupabase() {
  return createClient(process.env.SUPABASE_URL || '', process.env.SUPABASE_SERVICE_KEY || '');
}

// ============================================================
// CRUD Operations
// ============================================================

/**
 * Create a new deliverable
 */
export async function createDeliverable(
  input: CreateDeliverableInput
): Promise<Deliverable | null> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase
      .from('deliverables')
      .insert({
        deliverable_type: input.deliverable_type,
        title: input.title,
        owner_agent: input.owner_agent,
        opportunity_id: input.opportunity_id,
        opportunity_title: input.opportunity_title,
        content: input.content,
        source_post_ids: input.source_post_ids || [],
        metadata: input.metadata || {},
        status: 'ready', // Default to ready since we generate complete content
      })
      .select()
      .single();

    if (error) throw error;

    console.log(`[Deliverables] Created ${input.deliverable_type}: ${input.title}`);
    return data as Deliverable;
  } catch (err) {
    console.error('[Deliverables] Failed to create:', err);
    return null;
  }
}

/**
 * Get deliverable by ID
 */
export async function getDeliverable(id: string): Promise<Deliverable | null> {
  try {
    const supabase = getSupabase();
    const { data, error } = await supabase.from('deliverables').select('*').eq('id', id).single();

    if (error) throw error;
    return data as Deliverable;
  } catch (err) {
    console.error('[Deliverables] Failed to get:', err);
    return null;
  }
}

/**
 * Get recent deliverables
 */
export async function getRecentDeliverables(options?: {
  type?: DeliverableType;
  status?: DeliverableStatus;
  owner?: string;
  opportunityId?: string;
  limit?: number;
  sinceHoursAgo?: number;
}): Promise<Deliverable[]> {
  try {
    const supabase = getSupabase();
    let query = supabase.from('deliverables').select('*');

    if (options?.type) {
      query = query.eq('deliverable_type', options.type);
    }

    if (options?.status) {
      query = query.eq('status', options.status);
    }

    if (options?.owner) {
      query = query.eq('owner_agent', options.owner);
    }

    if (options?.opportunityId) {
      query = query.eq('opportunity_id', options.opportunityId);
    }

    if (options?.sinceHoursAgo) {
      const since = new Date(Date.now() - options.sinceHoursAgo * 60 * 60 * 1000).toISOString();
      query = query.gte('created_at', since);
    }

    query = query.order('created_at', { ascending: false });

    if (options?.limit) {
      query = query.limit(options.limit);
    }

    const { data, error } = await query;

    if (error) throw error;
    return (data || []) as Deliverable[];
  } catch (err) {
    console.error('[Deliverables] Failed to get recent:', err);
    return [];
  }
}

/**
 * Update deliverable status
 */
export async function updateDeliverableStatus(
  id: string,
  status: DeliverableStatus
): Promise<boolean> {
  try {
    const supabase = getSupabase();
    const { error } = await supabase
      .from('deliverables')
      .update({ status, updated_at: new Date().toISOString() })
      .eq('id', id);

    if (error) throw error;
    console.log(`[Deliverables] Updated ${id} status to ${status}`);
    return true;
  } catch (err) {
    console.error('[Deliverables] Failed to update status:', err);
    return false;
  }
}

/**
 * Update Notion page ID
 */
export async function updateDeliverableNotionId(
  id: string,
  notionPageId: string
): Promise<boolean> {
  try {
    const supabase = getSupabase();
    const { error } = await supabase
      .from('deliverables')
      .update({ notion_page_id: notionPageId, updated_at: new Date().toISOString() })
      .eq('id', id);

    if (error) throw error;
    return true;
  } catch (err) {
    console.error('[Deliverables] Failed to update Notion ID:', err);
    return false;
  }
}

// ============================================================
// Synthesis Tracking
// ============================================================

/**
 * Check if a discussion has already been synthesized
 */
export async function isDiscussionSynthesized(rootPostId: string): Promise<boolean> {
  try {
    const supabase = getSupabase();
    const { count, error } = await supabase
      .from('synthesized_discussions')
      .select('*', { count: 'exact', head: true })
      .eq('root_post_id', rootPostId);

    if (error) throw error;
    return (count || 0) > 0;
  } catch {
    return false;
  }
}

/**
 * Mark a discussion as synthesized
 */
export async function markDiscussionSynthesized(
  rootPostId: string,
  deliverableId: string
): Promise<boolean> {
  try {
    const supabase = getSupabase();
    const { error } = await supabase.from('synthesized_discussions').insert({
      root_post_id: rootPostId,
      deliverable_id: deliverableId,
    });

    if (error) {
      // Unique constraint violation means already synthesized
      if (error.code === '23505') {
        return true;
      }
      throw error;
    }

    return true;
  } catch (err) {
    console.error('[Deliverables] Failed to mark synthesized:', err);
    return false;
  }
}

// ============================================================
// Summary & Statistics
// ============================================================

/**
 * Get deliverables summary for a period
 */
export async function getDeliverablesSummary(sinceDays: number = 7): Promise<{
  total: number;
  byType: Record<DeliverableType, number>;
  byStatus: Record<DeliverableStatus, number>;
  byOwner: Record<string, number>;
}> {
  try {
    const supabase = getSupabase();
    const since = new Date(Date.now() - sinceDays * 24 * 60 * 60 * 1000).toISOString();

    const { data, error } = await supabase
      .from('deliverables')
      .select('deliverable_type, status, owner_agent')
      .gte('created_at', since);

    if (error) throw error;

    const summary = {
      total: data?.length || 0,
      byType: {} as Record<DeliverableType, number>,
      byStatus: {} as Record<DeliverableStatus, number>,
      byOwner: {} as Record<string, number>,
    };

    for (const row of data || []) {
      summary.byType[row.deliverable_type as DeliverableType] =
        (summary.byType[row.deliverable_type as DeliverableType] || 0) + 1;
      summary.byStatus[row.status as DeliverableStatus] =
        (summary.byStatus[row.status as DeliverableStatus] || 0) + 1;
      summary.byOwner[row.owner_agent] = (summary.byOwner[row.owner_agent] || 0) + 1;
    }

    return summary;
  } catch (err) {
    console.error('[Deliverables] Failed to get summary:', err);
    return {
      total: 0,
      byType: {} as Record<DeliverableType, number>,
      byStatus: {} as Record<DeliverableStatus, number>,
      byOwner: {},
    };
  }
}

// ============================================================
// Formatting Helpers
// ============================================================

const TYPE_EMOJI: Record<DeliverableType, string> = {
  go_no_go_memo: ':memo:',
  research_brief: ':books:',
  partner_shortlist: ':handshake:',
  tech_assessment: ':gear:',
  executive_insight: ':bulb:',
  capture_plan: ':clipboard:',
  weekly_rollup: ':calendar:',
};

const TYPE_LABEL: Record<DeliverableType, string> = {
  go_no_go_memo: 'Go/No-Go Memo',
  research_brief: 'Research Brief',
  partner_shortlist: 'Partner Shortlist',
  tech_assessment: 'Tech Assessment',
  executive_insight: 'Executive Insight',
  capture_plan: 'Capture Plan',
  weekly_rollup: 'Weekly Rollup',
};

/**
 * Format deliverable for Slack notification
 */
export function formatDeliverableForSlack(deliverable: Deliverable): string {
  const emoji = TYPE_EMOJI[deliverable.deliverable_type];
  const label = TYPE_LABEL[deliverable.deliverable_type];

  const lines = [
    `${emoji} *New ${label}*: ${deliverable.title}`,
    `Owner: ${deliverable.owner_agent.charAt(0).toUpperCase() + deliverable.owner_agent.slice(1)}`,
  ];

  if (deliverable.opportunity_title) {
    lines.push(`Opportunity: ${deliverable.opportunity_title}`);
  }

  // Include first 200 chars of content as preview
  if (deliverable.content) {
    const preview = deliverable.content.slice(0, 200).replace(/\n/g, ' ');
    lines.push(`\n> ${preview}${deliverable.content.length > 200 ? '...' : ''}`);
  }

  return lines.join('\n');
}

/**
 * Get type label for display
 */
export function getDeliverableTypeLabel(type: DeliverableType): string {
  return TYPE_LABEL[type];
}
