-- Team Playbook - Self-Organizing Process Evolution
-- The team's self-discovered rules, SOPs, and lessons learned
-- Not hardcoded by humans — generated by the team from their own data

-- ============================================================
-- Table: team_playbook
-- Where the team's self-discovered rules live
-- ============================================================
CREATE TABLE IF NOT EXISTS team_playbook (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Rule classification
  rule_type TEXT NOT NULL,  -- 'process_rule', 'threshold', 'preference', 'sop', 'lesson_learned'
  category TEXT NOT NULL,   -- 'pursuit_criteria', 'timeline', 'teaming', 'tech_assessment', 'proposal_process'

  -- The rule itself
  rule TEXT NOT NULL,  -- Human-readable: "Don't pursue opportunities with <30 days to respond"

  -- Evidence backing the rule
  evidence JSONB DEFAULT '{}',  -- Data: win rates, chain data, examples

  -- Confidence level (increases as more data supports it)
  confidence NUMERIC DEFAULT 0.5 CHECK (confidence >= 0 AND confidence <= 1),

  -- Origin
  proposed_by TEXT NOT NULL,  -- Which agent proposed this

  -- Status lifecycle
  status TEXT NOT NULL DEFAULT 'proposed',  -- 'proposed', 'active', 'retired', 'overridden_by_human'

  -- Timestamps
  adopted_at TIMESTAMPTZ,
  retired_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Outcome tracking
  supporting_outcomes UUID[] DEFAULT '{}',   -- Opportunity IDs that support this rule
  contradicting_outcomes UUID[] DEFAULT '{}', -- Opportunity IDs that contradict it

  -- Usage tracking
  times_applied INTEGER DEFAULT 0,
  times_overridden INTEGER DEFAULT 0,

  -- Override history
  override_history JSONB DEFAULT '[]'  -- Array of {overridden_at, reason, by}
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_playbook_active
  ON team_playbook(status, category)
  WHERE status = 'active';

CREATE INDEX IF NOT EXISTS idx_playbook_category
  ON team_playbook(category, status);

CREATE INDEX IF NOT EXISTS idx_playbook_proposed_by
  ON team_playbook(proposed_by);

CREATE INDEX IF NOT EXISTS idx_playbook_confidence
  ON team_playbook(confidence DESC)
  WHERE status = 'active';

-- ============================================================
-- Table: playbook_applications
-- Track when rules are applied or overridden
-- ============================================================
CREATE TABLE IF NOT EXISTS playbook_applications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  rule_id UUID NOT NULL REFERENCES team_playbook(id),
  opportunity_id TEXT,  -- notice_id of the opportunity
  opportunity_title TEXT,

  -- What happened
  action TEXT NOT NULL,  -- 'applied', 'overridden', 'ignored'
  applied_by TEXT NOT NULL,  -- Which agent applied it
  override_reason TEXT,  -- If overridden, why

  -- Context
  context JSONB DEFAULT '{}',  -- Additional context about the application

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_playbook_applications_rule
  ON playbook_applications(rule_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_playbook_applications_opportunity
  ON playbook_applications(opportunity_id);

-- ============================================================
-- Table: retrospective_runs
-- Track Patricia's retrospective analysis runs
-- ============================================================
CREATE TABLE IF NOT EXISTS retrospective_runs (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

  -- Period analyzed
  period_start TIMESTAMPTZ NOT NULL,
  period_end TIMESTAMPTZ NOT NULL,

  -- Results
  outcomes_analyzed INTEGER DEFAULT 0,
  chains_analyzed INTEGER DEFAULT 0,
  rules_proposed INTEGER DEFAULT 0,
  rules_adopted INTEGER DEFAULT 0,

  -- Findings
  findings JSONB DEFAULT '{}',  -- Summary of what was discovered

  -- Status
  status TEXT DEFAULT 'running',  -- 'running', 'completed', 'failed'

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- ============================================================
-- Function: propose_rule()
-- Agent proposes a new rule based on data analysis
-- ============================================================
CREATE OR REPLACE FUNCTION propose_rule(
  p_rule_type TEXT,
  p_category TEXT,
  p_rule TEXT,
  p_evidence JSONB,
  p_proposed_by TEXT,
  p_confidence NUMERIC DEFAULT 0.5
)
RETURNS UUID
LANGUAGE plpgsql
AS $$
DECLARE
  v_existing_id UUID;
  v_rule_id UUID;
BEGIN
  -- Check if a similar rule already exists (same category and similar text)
  SELECT id INTO v_existing_id
  FROM team_playbook
  WHERE category = p_category
    AND status IN ('proposed', 'active')
    AND similarity(rule, p_rule) > 0.7  -- PostgreSQL pg_trgm similarity
  LIMIT 1;

  IF v_existing_id IS NOT NULL THEN
    -- Update existing rule with new evidence
    UPDATE team_playbook
    SET
      evidence = evidence || p_evidence,
      confidence = LEAST(1.0, confidence + 0.1),
      updated_at = NOW()
    WHERE id = v_existing_id;

    RETURN v_existing_id;
  END IF;

  -- Create new rule
  INSERT INTO team_playbook (
    rule_type,
    category,
    rule,
    evidence,
    proposed_by,
    confidence,
    status
  ) VALUES (
    p_rule_type,
    p_category,
    p_rule,
    p_evidence,
    p_proposed_by,
    p_confidence,
    'proposed'
  )
  RETURNING id INTO v_rule_id;

  RETURN v_rule_id;
END;
$$;

-- ============================================================
-- Function: adopt_rule()
-- Human adopts a proposed rule, making it active
-- ============================================================
CREATE OR REPLACE FUNCTION adopt_rule(p_rule_id UUID)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE team_playbook
  SET
    status = 'active',
    adopted_at = NOW(),
    updated_at = NOW()
  WHERE id = p_rule_id
    AND status = 'proposed';

  RETURN FOUND;
END;
$$;

-- ============================================================
-- Function: retire_rule()
-- Retire a rule that's no longer valid
-- ============================================================
CREATE OR REPLACE FUNCTION retire_rule(
  p_rule_id UUID,
  p_reason TEXT DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  UPDATE team_playbook
  SET
    status = 'retired',
    retired_at = NOW(),
    updated_at = NOW(),
    evidence = CASE
      WHEN p_reason IS NOT NULL
      THEN evidence || jsonb_build_object('retirement_reason', p_reason)
      ELSE evidence
    END
  WHERE id = p_rule_id
    AND status = 'active';

  RETURN FOUND;
END;
$$;

-- ============================================================
-- Function: override_rule()
-- Human overrides a rule for a specific opportunity
-- ============================================================
CREATE OR REPLACE FUNCTION override_rule(
  p_rule_id UUID,
  p_opportunity_id TEXT,
  p_reason TEXT,
  p_overridden_by TEXT DEFAULT 'human'
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  -- Record the override in applications
  INSERT INTO playbook_applications (
    rule_id,
    opportunity_id,
    action,
    applied_by,
    override_reason
  ) VALUES (
    p_rule_id,
    p_opportunity_id,
    'overridden',
    p_overridden_by,
    p_reason
  );

  -- Update rule's override count and history
  UPDATE team_playbook
  SET
    times_overridden = times_overridden + 1,
    override_history = override_history || jsonb_build_array(
      jsonb_build_object(
        'overridden_at', NOW(),
        'reason', p_reason,
        'by', p_overridden_by,
        'opportunity_id', p_opportunity_id
      )
    ),
    updated_at = NOW()
  WHERE id = p_rule_id;

  RETURN TRUE;
END;
$$;

-- ============================================================
-- Function: apply_rule()
-- Record that a rule was applied to an opportunity
-- ============================================================
CREATE OR REPLACE FUNCTION apply_rule(
  p_rule_id UUID,
  p_opportunity_id TEXT,
  p_opportunity_title TEXT,
  p_applied_by TEXT,
  p_context JSONB DEFAULT '{}'
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  -- Record the application
  INSERT INTO playbook_applications (
    rule_id,
    opportunity_id,
    opportunity_title,
    action,
    applied_by,
    context
  ) VALUES (
    p_rule_id,
    p_opportunity_id,
    p_opportunity_title,
    'applied',
    p_applied_by,
    p_context
  );

  -- Update rule's application count
  UPDATE team_playbook
  SET
    times_applied = times_applied + 1,
    updated_at = NOW()
  WHERE id = p_rule_id;

  RETURN TRUE;
END;
$$;

-- ============================================================
-- Function: get_active_rules()
-- Get active rules for a category with minimum confidence
-- ============================================================
CREATE OR REPLACE FUNCTION get_active_rules(
  p_category TEXT DEFAULT NULL,
  p_min_confidence NUMERIC DEFAULT 0.6
)
RETURNS TABLE (
  id UUID,
  rule_type TEXT,
  category TEXT,
  rule TEXT,
  evidence JSONB,
  confidence NUMERIC,
  proposed_by TEXT,
  adopted_at TIMESTAMPTZ,
  times_applied INTEGER,
  times_overridden INTEGER
)
LANGUAGE sql
AS $$
  SELECT
    id,
    rule_type,
    category,
    rule,
    evidence,
    confidence,
    proposed_by,
    adopted_at,
    times_applied,
    times_overridden
  FROM team_playbook
  WHERE status = 'active'
    AND confidence >= p_min_confidence
    AND (p_category IS NULL OR category = p_category)
  ORDER BY confidence DESC, adopted_at ASC;
$$;

-- ============================================================
-- Function: check_rule_health()
-- Check if rules should be retired based on override frequency
-- ============================================================
CREATE OR REPLACE FUNCTION check_rule_health()
RETURNS TABLE (
  rule_id UUID,
  rule_text TEXT,
  override_rate NUMERIC,
  should_retire BOOLEAN,
  should_boost BOOLEAN
)
LANGUAGE sql
AS $$
  SELECT
    id AS rule_id,
    rule AS rule_text,
    CASE
      WHEN times_applied > 0 THEN times_overridden::NUMERIC / times_applied
      ELSE 0
    END AS override_rate,
    -- Retire if overridden more than 40% of the time with 5+ applications
    (times_applied >= 5 AND times_overridden::NUMERIC / times_applied > 0.4) AS should_retire,
    -- Boost confidence if many supporting outcomes and few contradictions
    (array_length(supporting_outcomes, 1) > 10 AND array_length(contradicting_outcomes, 1) < 2) AS should_boost
  FROM team_playbook
  WHERE status = 'active';
$$;

-- ============================================================
-- Function: update_rule_outcomes()
-- Add supporting or contradicting outcome to a rule
-- ============================================================
CREATE OR REPLACE FUNCTION update_rule_outcomes(
  p_rule_id UUID,
  p_opportunity_id UUID,
  p_supports BOOLEAN  -- TRUE = supports, FALSE = contradicts
)
RETURNS BOOLEAN
LANGUAGE plpgsql
AS $$
BEGIN
  IF p_supports THEN
    UPDATE team_playbook
    SET
      supporting_outcomes = array_append(supporting_outcomes, p_opportunity_id),
      confidence = LEAST(1.0, confidence + 0.02),
      updated_at = NOW()
    WHERE id = p_rule_id;
  ELSE
    UPDATE team_playbook
    SET
      contradicting_outcomes = array_append(contradicting_outcomes, p_opportunity_id),
      confidence = GREATEST(0.1, confidence - 0.05),
      updated_at = NOW()
    WHERE id = p_rule_id;
  END IF;

  RETURN FOUND;
END;
$$;

-- ============================================================
-- Enable pg_trgm extension for similarity matching
-- ============================================================
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- ============================================================
-- Enable RLS
-- ============================================================
ALTER TABLE team_playbook ENABLE ROW LEVEL SECURITY;
ALTER TABLE playbook_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE retrospective_runs ENABLE ROW LEVEL SECURITY;

-- Service role access policies
CREATE POLICY "Service role access for team_playbook"
  ON team_playbook
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role access for playbook_applications"
  ON playbook_applications
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Service role access for retrospective_runs"
  ON retrospective_runs
  FOR ALL
  TO service_role
  USING (true)
  WITH CHECK (true);

-- ============================================================
-- Comments
-- ============================================================
COMMENT ON TABLE team_playbook IS 'Self-discovered rules, SOPs, and lessons learned by the AI BD team based on actual win/loss data.';
COMMENT ON TABLE playbook_applications IS 'Track when playbook rules are applied or overridden for specific opportunities.';
COMMENT ON TABLE retrospective_runs IS 'Track Patricia''s monthly retrospective analysis runs.';
COMMENT ON FUNCTION propose_rule IS 'Agent proposes a new rule based on data analysis. Merges with similar existing rules.';
COMMENT ON FUNCTION adopt_rule IS 'Human adopts a proposed rule, making it active for team use.';
COMMENT ON FUNCTION override_rule IS 'Human overrides a rule for a specific opportunity, tracking the override.';
COMMENT ON FUNCTION get_active_rules IS 'Get active rules for agents to consult before decisions.';
COMMENT ON FUNCTION check_rule_health IS 'Check if rules should be retired based on override frequency.';
